plugins {
	id 'com.android.library'
}

android {
	namespace 'com.strivacity.android.native_sdk'
	compileSdk 36

	buildFeatures {
		buildConfig true
	}

	defaultConfig {
		minSdk 29
		targetSdk 36

		testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
		buildConfigField "String", "STRIVACITY_SDK_VERSION", "\"${project.hasProperty('sdkVersion') ? project.sdkVersion : '0.0.0'}\""
	}

	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
		}
	}
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_1_8
		targetCompatibility JavaVersion.VERSION_1_8
	}
}

dependencies {

	implementation libs.appcompat
	implementation libs.material
	implementation libs.activity
	implementation libs.browser
	implementation libs.constraintlayout
	// Credentials API for lvl 33+
	implementation libs.credentials
	// Credentials API for lvl [28;33]
	implementation libs.credentials.playservices
	testImplementation libs.junit
	androidTestImplementation libs.ext.junit
	androidTestImplementation libs.espresso.core

	compileOnly libs.org.projectlombok.lombok
	annotationProcessor libs.org.projectlombok.lombok
}
